# Site settings
title: MFeuer's Tech Blog
header-img: img/home-bg.png
email: mallory.feuer@gmail.com
copyright_name: MFeuer23
description: > # this means to ignore newlines until "baseurl:"
  Woman Takes Tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MFeuer23
learn_profile: MFeuer23
email_username: mallory.feuer@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
